autoload/OmniSharp.vim
I have been working in a project that had one directory ending with '.sln' (wasn't me who created, but was there).
OmniSharp-Vim was passing this directory's path to Server as the solution file, causing wrong behavior to it. I know it is not a usual situation, but it can happen.
=> Fix to prevent OmniSharp-Vim from treating a directory ended with '.sln'

python/OmniSharp.py
Allows omnisharp-vim to work with the v1 server and omnisharp-roslyn
=> Use application/json for Python http requests from vim

.gitmodules, autoload/OmniSharp.vim
Added omnisharp-roslyn as a module and starting it up by pointing it to directory containing project.json. To switch - set variable in autoload/Omnisharp.vim. Stopserver for roslyn a hack. Generally the code can be cleaned up once roslyn server has more command support.
=> Initial support for omnisharp-roslyn

autoload/OmniSharp.vim, ftplugin/cs/OmniSharp.vim, plugin/OmniSharp.vim, syntax_checkers/cs/codecheck.vim, syntax_checkers/cs/issues.vim, syntax_checkers/cs/semantic.vim, syntax_checkers/cs/syntax.vim
I have no idea what I'm doing when it comes to VimScript. I just know that I wanted to contribute something to a plugin that I'm using every single day. Issue #183 looked like something simple. 
I've added functionality to not register functions reliant on python if Vim is not compiled with +python.
To plugin/OmniSharp.vim I've also added a friendly error indicating that OmniSharp requires Vim with +python. 
If I've done something obviously foolish please let me know and I'll try and sort it out. 
Thanks everyone for creating and maintaining this plugin.
=> #183 Add checks before exporting functionality that requires python

python/OmniSharp.py
This is the first part of a patch to fix building the solution via the server.
The client was not parsing the result correctly.
The second part will contain fixes on the server to correctly parse errors/warnings, which it doesn't at the moment as it always returns a failed build.
=> Fixed OmniSharpBuild function which was not parsing result correctly

autoload/OmniSharp.vim
* Open csharp file foo.cs associated with multiple solution files
_ foo.cs
_ foo.sln
_ foo2.sln
* Server will then be started (provided autostart flag is set to 1)
* Stop server (:OmniSharpStopServer)
* Try starting server again :OmniSharpStartServer
Prompt will be empty :
> sln:
Server is **not started**
See https://github.com/OmniSharp/omnisharp-vim/blob/69a43ce9db692bc7d11fcac54df4c0c518c559c6/autoload/OmniSharp.vim#L476
It is checking variable g:OmniSharp_running_slns which is not cleared when server is stopped.
Clear g:OmniSharp_running_slns when server is stopped.
=> Fixed issue where server could not start after manually stopping it

autoload/OmniSharp.vim
When building a "-config" parameters, Fixed a bug that path to the configuration file is not escape.
=> called shellescape with configPath

autoload/OmniSharp.vim
I have report the bug at  https://github.com/OmniSharp/omnisharp-vim/issues/238
Fix TypeLookUpInPreview buffer will replace other "buftype=nofile"  (e.g. [Tagbar](https://github.com/majutsushi/tagbar), [VimFiler](https://github.com/Shougo/vimfiler.vim))  window. 
Use buffer named `__OmniSharpScratch__` instead.
Fix all method use 'quickfix'  `FindUsages`, `FindMembers` etc.  ,  which will goto and replae the right bottom window.  see http://vimdoc.sourceforge.net/htmldoc/quickfix.html#:cwindow
all use 'botright {cmd}'
`wincmd p` will jump back to other window, so I defined a local variable `preWinNr` to store winnr, and restore it later.
Changes to be committed:
modified:   autoload/OmniSharp.vim
=> TypeLookUpInPreview and quickfix buffer confilct and jump to other vertical window

syntax/cs.vim
C# 6 recently introduced 2 new keywords: `nameof` and `when`. This commit adds them to the `cs.vim` file so they get syntax highlighting.
=> Add support for new C# 6 keywords

README.md, autoload/OmniSharp.vim, ftplugin/cs/OmniSharp.vim, plugin/OmniSharp.vim, python/Completion.py
I don't think I'm 100% complete with this pull request yet but I wanted to create it so that its gets some visibility. Even more so because I'm new to Vim and Vim Script development. 
This pull request adds support for #206, on the fly generation and expansion of snippets during code completion. 
There are some requirements:
1. UltiSnips is installed
2. set completeopt does not specify "preview". This causes known issues with UltiSnips since the preview temporary steals focus and breaks snippets
3. The user configures omnisharp completion to make use of snippets, return type and method header in their .vimrc
```
let g:omnicomplete_want_snippet=1
let g:omnicomplete_want_return_type=1
let g:omnicomplete_want_method_header=1
```
4. An autocmd to activate snippet expansion
```
autocmd …
```
=> #206 Support for on the fly generation and expansion of snippets during completion

python/Completion.py
While testing omnisharp-vim with the latest roslyn server I got an error on autocomplete when Description is null. This PR should fix the problem.
=> Fix error when Description of autocomplete response is null

syntax/cs.vim
`@class` and `@new` can be used now without further issue.
=> Fix verbatim identifiers breaking highlights

autoload/OmniSharp.vim, plugin/OmniSharp.vim
This pull request is useful when working with multiple projects in this structure:
```
/unit-testing-using-dotnet-test
|__global.json
|__/src
|__/PrimeService
|__Source Files
|__project.json
|__/test
|__/PrimeService.Tests
|__Test Files
|__project.json
```
If we tell omnisharp to use the same directory that `global.json` is in for the solution, it will provide completion for all contained `project.json` files, instead of just one.
First, it adds the variable `g:OmniSharp_prefer_global_sln` with a default of 0.
If a user sets this to 1, then when omnisharp-vim is looking for sln files, it will also look for a `global.json` file. If it finds one, it will start the server using `global.json`'s directory as the solution.
When `g:OmniSharp_prefer_global_sln` is set to 0, there is no difference …
=> Add support for global.json when looking for sln files.

autoload/OmniSharp.vim
Following up on https://github.com/OmniSharp/omnisharp-vim/issues/244 - omnisharp-vim does not work in my environment, so I thought I'd at least add some information about what happened when JSON parsing fails. It simply says whether there was a response or not, and if the response is invalid, print it.
=> Provide more information when server returns empty/invalid JSON

plugin/OmniSharp.vim
Doing this makes sure that someone can do something like 
the following in their .vimrc to automatically disable omnisharp
if vim is loaded without seeing error messages:
if !has("python")
let g:OmniSharp_loaded = 1
endif
=> Move check for python to happen after OmniSharp_loaded check

autoload/OmniSharp.vim
I'm not sure if I messed something up to cause these to be empty but Neovim is complaining about these calls when they are.
I'm using the roslyn server if that makes a difference.
=> Guard Highlighting to prevent errors in Neovim

autoload/OmniSharp.vim, plugin/OmniSharp.vim
Currently, roslyn server doesn't work on Windows since command name contains slashs. Also `.cmd` is missing.
=> Fix command name on Windows

plugin/OmniSharp.vim
This is a tiny addon to @mattn's previous PR - it just includes cygwin (`has('win32unix')`) when adding `.cmd` to the executable path
=> Check for cygwin when adding .cmd to path

autoload/OmniSharp/util.vim
In the recent refactorings, the path to the omnisharp-roslyn server executable has been changed from 'OmniSharp' to 'Omnisharp'. This changes it back.
=> Rename server_path from Omnisharp to OmniSharp

python/OmniSharp.py
The rolsyn server returns json containing "FileName": "null" from /currentfilemembersasflat in a call to OmniSharpFindMembers - presumably since this method only applies to the current file.
The "null" value can't be read by vim, so "null" filenames are replaced with the current buffer name.
=> Interpret "null" FileName response as current file

README.md, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim
The README and :help documentation describe variable `g:omnisharp_fetch_documentation` but in code it is actually called `g:omnisharp_fetch_full_documentation`.
=> Make fetch_full_documentation match README & help

autoload/OmniSharp/proc.vim
The case that set filetype immediately twice, for example, if I'm very fast to open the two C# files. Server will be spawned twice. And the second server throw exception `EADDRINUSE address already in use`. This change avoid to spawn the server if the job still exists.
=> Avoid to spawn server twice

syntax/cs.vim
The omnisharp syntax file was copied from the standard vimfiles, but
it's had some heavy modifications despite "last change" being 2009.
Add OmniSharp as a Maintainer and strip out the version lines to help
others find their way back to this repo and make it clearer that the
file isn't stock.
I was confused when looking through my C# syntax files: I had what appeared to be three identical ones because I had also copied the vimfiles one. But all three had different contents. This change hopes to prevent similar confusion for others.
=> Superficial: Remove incorrect version information from syntax

autoload/OmniSharp.vim, autoload/ctrlp/OmniSharp/findcodeactions.vim, autoload/fzf/OmniSharp.vim, python/OmniSharp.py
When using the roslyn server, use the `/v2/getcodeactions` endpoint instead of the old `/getcodeactions`.
I have only implemented this for fzf, but it would be trivial to implement for ctrlp and unite based on this PR. I can add CtrlP support but I don't have experience with unite so I'd prefer someone else do it?
=> Use roslyn /v2/getcodeactions

autoload/OmniSharp.vim, autoload/ctrlp/OmniSharp/findsymbols.vim, autoload/fzf/OmniSharp.vim, python/OmniSharp.py
The roslyn /findsymbols endpoint requires a 'Filter' parameter, which may be an empty string.
This PR also adds the ability to add a filter, when using fzf, i.e. `:call OmniSharp#FindSymbol('IAbstract')` to filter the output. This is probably of limited value, but roslyn offers the functionality so we might as well use it.
=> Fix /findsymbols bug with roslyn server

autoload/OmniSharp.vim, python/OmniSharp.py
The roslyn server does not have the /lookupalltypes endpoint that the OmniSharpHighlightTypes functionality relies on. This change uses the /findsymbols endpoint instead.
=> Add roslyn server OmniSharpHighlightTypes support

README.md, plugin/OmniSharp.vim, python/OmniSharp.py
i work with multiple projects open at the same time. having the default port set to 2000 causes conflicts - opening ProjectA works fine but opening ProjectB requires a bit of manual work to hook up omni.
this pr allows allows a new setting (g:OmniSharp_use_random_port) to be defined. if set to a truthy value, a random port will be used during OmniSharp startup.
=> allow use of a random port during omnisharp startup

python/OmniSharp.py
when a code action does things in a file other than the current buffer, nothing happens. here's a fix for that ... seems to work as best i tested it.
a few things 
- is there a test suite to run ensuring i am not breaking anything?
- not sure what to do when a new file is opened. should the user be taken back to the buffer from where the code action was run? should the new file be saved automatically? right now the user is left in the new file that was created, the file is not saved.
- my python is non-existent so if there's a better way to accomplish this don't hesitate to let me know / change it.
thx
=> handle code actions requiring a separate file than the current buffer

autoload/OmniSharp.vim
OmniSharp Server requires paths to be absolute
=> Bug fix: Use absolute paths

.travis.yml, appveyor.yml, autoload/OmniSharp.vim, autoload/OmniSharp/lib/py.vim, autoload/OmniSharp/py.vim, autoload/ctrlp/OmniSharp/findcodeactions.vim, autoload/ctrlp/OmniSharp/findsymbols.vim, autoload/ctrlp/OmniSharp/findtype.vim, autoload/fzf/OmniSharp.vim, autoload/unite/sources/OmniSharp.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim, plugin/OmniSharp.vim, python/.pylintrc, python/omnisharp/OmniSharp.py, python/tests/mock_vim.py, python/tests/test_vim.py, python/tox.ini, syntax_checkers/cs/codecheck.vim, syntax_checkers/cs/issues.vim, syntax_checkers/cs/semantic.vim, syntax_checkers/cs/syntax.vim
I am trying to get this working again.
I am raising this PR as `omnisharp-vim` is the last plugin, that is requiring me to have python 2 installed.  This depends on #287 as #287 adds the necessary infrastructure to test the python mod
Features I'd like to see getting merged:
It would be great to hear any feedback on whether we want to support both Python versions.
**NOTE**: Since #275 is quite big, I would prefer it to be merged before dealing with this and #287.
Currently rebased on `feature/pytest` for easier testing.
=> [RFC] Python 3 support

README.md, autoload/OmniSharp.vim, autoload/OmniSharp/proc.vim, autoload/OmniSharp/py.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim, plugin/OmniSharp.vim, python/omnisharp/OmniSharp.py, python/tests/mock_vim.py, test/run-omnisharp-async.vader
This PR adds a new variable to allow disabling automatically opening the quickfix window after FindUsages, FindImplementations etc.
There is also some minor refactoring, including renaming variables to make casing consistent throught the project - all variables called `g:Omnisharp_...` and `:g:omnisharp_...` have been renamed to `g:OmniSharp_...`
=> Option to open quickfix

autoload/OmniSharp.vim, python/omnisharp/OmniSharp.py
Also, I had to change the call to `setqflist()`. The 'items' key is a [pretty recent addition](https://github.com/vim/vim/commit/6a8958db259d4444da6e6956e54a6513c1af8860) to vim and [even more recent](https://github.com/neovim/neovim/commit/d0c4bd23f78ee00943725ea77a63f2a223dba66b) in neovim. When it isn't supported, the set will silently fail.
There is another syntax where instead of providing a dict as the third argument you just pass in the title. Modern vim is backwards compatible with it, and it will throw if it fails which allows us to more easily support older versions (like 7.4)
=> Shorten the filenames in quickfix

README.md, autoload/OmniSharp.vim, autoload/OmniSharp/proc.vim, autoload/OmniSharp/util.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim, plugin/OmniSharp.vim, python/omnisharp/OmniSharp.py
I was doing a lot of work on projects with different solution files simultaneously, and omnisharp-vim wasn't handling it well.
The main focus of this change was making it so that instead of using a single omnisharp-roslyn server, we do everything on a per-solution-file basis. Servers are started per-solution. Ports are mapped per-solution.
A side effect of this change is that now servers are started on a random port by default, though this is configurable with `g:OmniSharp_sln_ports`.
=> Support running multiple OmniSharp servers

README.md, ale_linters/cs/omnisharp.vim, autoload/OmniSharp.vim, python/ale_lint.py
Most of this is pretty straightforward. Just adding a standalone python script that can perform the lint, and the glue file that tells ALE how to use it.
I did some refactoring in `autoload/OmniSharp.vim` because ALE passes the buffer number as an argument. I don't know if that means that ALE might be called on buffers that aren't the current buffer...but I assumed that might be the case and changed some of the utility functions (like `OmniSharp#FindSolution()`) to optionally take a buffer number instead of always assuming the current buffer.
=> Add ALE support

README.md, autoload/OmniSharp.vim, autoload/OmniSharp/util.vim, doc/omnisharp-vim.txt
This is a followup to #382, updating the default location for the OmniSharp-roslyn server when no `g:OmniSharp_server_path` is set, and prompting the user to download and extract the latest binaries when the server does not exist.
=> Set default path to server, and prompt to install

ale_linters/cs/omnisharp.vim, ftplugin/cs/OmniSharp.vim, syntax_checkers/cs/codecheck.vim
Support the common vim idiom for disabling a plugin:
let g:OmniSharp_loaded = 0
Any vimscript that might execute on its own should ensure loaded is
greater than zero.
While omnisharp is generally great at silently failing if the server
doesn't exist, this allows users to easily turn it off when necessary.
Without this change, setting loaded to zero causes lots of errors when editing a .cs file. With this change,  no errors.
=> Allow users to disable omnisharp

autoload/ctrlp/OmniSharp/findsymbols.vim, autoload/fzf/OmniSharp.vim
Fix an error after you validate an entry during a :OmniSharpFindSymbols.
Occurs only if g:OmniSharp_selector_ui is 'ctrlp' or 'fzf'.
Error message for fzf was:
Error detected while processing function OmniSharp#FindSymbol[17]..fzf#OmniSharp#findsymbols[6]..fzf#run[69]..<SNR>49_callback:
line   33:
Vim(call):E119: Not enough arguments for function: OmniSharp#JumpToLocation
Error detected while processing function OmniSharp#FindSymbol:
line   17:
E171: Missing :endif
Press ENTER or type command to continue
=> Fix :OmniSharpFindSymbols error when validating

autoload/OmniSharp.vim, autoload/OmniSharp/util.vim, ftplugin/cs/OmniSharp.vim, installer/omnisharp-manager.sh
This pull request adds two new features to to the `OmniSharpInstall` command.
If the variable `g:OmniSharp_server_use_mono` is set to `1`, the automatic installer and the `OmniSharpInstall` command will install the mono variant of the OmniSharp Roslyn server.
The `OmniSharpInstall` command now accepts an optional parameter which will allow a specific version of OmniSharp Roslyn to be installed:
e.g.
```vim
:OmniSharpInstall 'v1.32.1'
```
=> Mono installer & install specific versions

python/omnisharp/util.py
I'm working on a project that uses a bunch of windows junctions and a csproj that refers to the symlinked path. When I edit the symlinked files I need to pass the symlinked path because that is the one that omnisharp expects.
`vim.current.buffer.name` is always the real path (tested in vim and neovim)
`vim.eval("expand('%:p')")` will give us the correct, symbolic path
=> Preserve symlinked path

autoload/OmniSharp.vim, installer/README.md, installer/omnisharp-manager.ps1
This addresses an issue where PowerShell was failing to install the OmniSharp Roslyn server but OmniSharp-vim was confirming the installation. It also addresses the slow install of the server on Windows by disabling the PowerShell UI updates during download.
=> Addressing issue #404 with Roslyn Server not installing

README.md
👋 
After I followed the documentation to get started with OmniSharp, I faced an issue where the OmniSharp server installed by the vim plugin could not start.  
I tried to run it manually, and figured out that it could not run because of libuv package missing, even if I already installed it using `apt-get install libuv1'.    
A little search, and found this comment: https://github.com/OmniSharp/omnisharp-roslyn/issues/1144#issuecomment-379270906  
The libuv dev package is needed.   
And `apt-cache search libuv` command returns no `libuv` package, but the following:
```
libuv1 - asynchronous event notification library - runtime library
libuv1-dbg - asynchronous event notification library - debugging symbols
libuv1-dev - asynchronous event notification library - development files
```
So the …
=> Update package name required in Debian

ale_linters/cs/omnisharp.vim, python/ale_lint.py
The output of the ALE linter is currently generated via vanilla `print()`.  
However, its encoding should be considered since vim's `&encoding` and the encoding of stdout often do not match. (e.g. on Windows, if you use normal Python for Windows, output encoding is cp932, but utf-8 is common for vim's `&encoding` nowadays.)  
This mismatch leads garbling of ALE's linting messages.
This PR makes output of the ALE linter vim's `&encoding`.
=> Fix encoding of stdout for ALE linter

python/ale_lint.py
As mentioned in https://github.com/OmniSharp/omnisharp-vim/commit/96128451b72c1e4718701c620f6f0dac6544c9ab#commitcomment-30803911, #418 is not python2 compatible. I'm sorry for that.
This PR is fix for that. But I'm afraid that I could not test it well. Could you please test it whether it runs with python2 without any error?
=> Fix of #418 (Make python2 compatible)

python/omnisharp/commands.py
Fix #412 
Tested and rename function still works, though I never experienced the crash so it would be great to get validation that it actually fixes the issue
=> Fix #412: Rename function fails on OSX

README.md, autoload/OmniSharp.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim, plugin/OmniSharp.vim, python/omnisharp/commands.py
The previous highlighting functionality was very limited - all classes and interfaces declared in the solution were added as solution-wide keywords.
Instead, use the roslyn-provided syntax highlighting. This entails parsing the highlighting information provided by OmniSharp-roslyn (a json file containing line/column groupings describing syntax fragments), extracting the interesting parts (class and interfaces), then reading the relevant spans from the buffer into an array of type name strings.
The result is much more comprehensive highlighting coverage, but at an efficiency cost.
=> Type highlighting

autoload/OmniSharp.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim, python/omnisharp/commands.py
A function for displaying the definition of the symbol under the cursor in the preview window already exists. This PR adds a function for displaying the implementation of the symbol under the cursor in the preview window. When more than one implementation exist, the first is displayed, and the number of implementations is echoed.
=> Display an implementation in the preview window

README.md, autoload/OmniSharp.vim, doc/omnisharp-vim.txt, installer/omnisharp-manager.sh
Various enhancements to the installer for Unix-like OSs, includes:
- Check for any errors during the installation process and display the
error messages in Vim.
- Add help message, to the script.
- Use either `curl` or `wget` depending on which is available.
- Use `tar` (& `gzip`) or `unzip` depending on which is installed.
=> Display error messages when installing OmniSharp-Roslyn on Unix-like OSs

autoload/OmniSharp.vim
Maybe cwindow default height is better.
cwindow 4 is too short.
=> Remove cwindow height parameter

autoload/OmniSharp.vim, ftplugin/cs/OmniSharp.vim, python/omnisharp/commands.py
This PR contains various highlighting improvements and bugfixes. It adds several new/updated OmniSharp-roslyn highlight "kinds, and ensures that highlight groups don't collide with vim keywords.
There are also some improvements to how the plugin checks for vim-fugitive buffers, to prevent errors when attempting to highlight or update a fugitive buffer.
Closes #397
=> Highlight syn options

installer/omnisharp-manager.ps1, installer/omnisharp-manager.sh
If users want to know what version they have (for bug reporting), there
is no obvious method. Now we store the downloaded version in a text
file.
Tested on gvim 8.1 on Windows.
Write the version file inside of the install folder so if different locations are used, it still works. Using a filename referencing the specific vim command to ensure uniqueness.
=> Store version information from OmniSharpInstall

autoload/coc/source/OmniSharp.vim
I didn't see any obvious way to hook up Omnisharp completions to coc.nvim without either using the not fully featured lsp mode or the omnifunc source, which isn't recommended.  So, I thought I'd put together a very simple completion source to see if I was on the right track for what I should do.
Does this seem right, and should it work for everyone else, too?
=> Added simple CoC completion source.

installer/omnisharp-manager.sh
I ran into issues using the roslyn auto-install option. It appears to have been related to obtaining the version. I'm not entirely certain why this wasn't working, but using -E fixes the issue with the added bonus IMO of making the regular expression easier to read.
```
$ curl --silent "https://api.github.com/repos/OmniSharp/omnisharp-roslyn/releases/latest" | grep '"tag_name":' | sed 's/.*"\([^"]\+\)".*/\1/'
"tag_name": "v1.32.18",
$ curl --silent "https://api.github.com/repos/OmniSharp/omnisharp-roslyn/releases/latest" | grep '"tag_name":' | sed 's/.*"\([^"]+\)".*/\1/'
"tag_name": "v1.32.18",
$ curl --silent "https://api.github.com/repos/OmniSharp/omnisharp-roslyn/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
v1.32.18
```
=> Use sed's -E option to fix & simplify regular expression.

autoload/OmniSharp.vim, ftdetect/csx.vim
Detect .csx files as filetype=cs, and automatically start the server for the current directory for .csx files when no .sln is found.
Closes #463
=> Support csx

python/omnisharp/commands.py
While trying to run :OmniSharpGetCodeActions in visual mode I was getting errors. This seems to be because the third element in the array returned from `vim.eval('getpos("\'>")')` is a very large number. The second item seems to be the correct number.
This fix worked for me. May be worth looking into. I am not great at Python, so it's possible I'm just missing something.
Thanks,
=> Change selected index of array item coming from vim.eval

.travis.yml, README.md, ale_linters/cs/omnisharp.vim, appveyor.yml, autoload/OmniSharp.vim, autoload/OmniSharp/proc.vim, autoload/OmniSharp/py.vim, autoload/OmniSharp/stdio.vim, autoload/OmniSharp/util.vim, autoload/ale/sources/OmniSharp.vim, autoload/asyncomplete/sources/OmniSharp.vim, autoload/ctrlp/OmniSharp/findcodeactions.vim, autoload/ctrlp/OmniSharp/findsymbols.vim, autoload/fzf/OmniSharp.vim, autoload/unite/sources/OmniSharp.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim, plugin/OmniSharp.vim, python/omnisharp/commands.py, python/tox-appveyor.ini, syntax_checkers/cs/codecheck.vim, test/run-omnisharp-async.vader
This is a work in progress PR to track work on switching from the HTTP OmniSharp-roslyn server to the Stdio version. This functionality will initially be "opt-in", with HTTP remaining the default.
My goal is to simultaneously remove OmniSharp-vim's python requirement, since the primary use of python is to handle HTTP connections and interactions. Vim8 and neovim can talk to the stdio processes natively (and asynchronously) with their respective job frameworks.
The current state is working well, with nearly all endpoints implemented. Only Vim8 support has been added so far, no neovim yet. Async functionality such as `HighlightBuffer` and completion with asyncomplete in particular work very smoothly compared to the synchronous HTTP versions, and the CountCodeActions flag system described in …
=> Async stdio

autoload/OmniSharp/stdio.vim, autoload/ale/sources/OmniSharp.vim
This PR listens to Diagnostic events from the server. In some situations (especially after an undo), a `/codecheck` event contains old diagnostics, and a followup Diagnostic event contains the updated diagnostics. These will now be caught and the ALE diagnostics updated (when ALE is in use only).
=> Listen for Diagnostic events and trigger ALE

autoload/OmniSharp.vim
I was getting an exception when using omnisharp omnifunc with ncm2, since this function was returning 0 (since no explicit return was included)
=> Fixed bug that was occuring when using synchronous omnifunc completion

README.md, autoload/OmniSharp.vim, autoload/OmniSharp/stdio.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim, plugin/OmniSharp.vim
This PR replaces the regex-based symantic highlighting with Vim8.1 text properties.
Closes #453
=> Use text properties for symantic highlighting

autoload/OmniSharp/proc.vim, autoload/OmniSharp/stdio.vim, doc/omnisharp-vim.txt, plugin/OmniSharp.vim
Add a 30 second (configurable) timeout when loading a server. If the "Successfully loaded project" server notifications are not received in this time, mark the server as "loaded" and allow sending requests.
=> Add server loading timeout

autoload/OmniSharp.vim, autoload/OmniSharp/stdio.vim, autoload/OmniSharp/util.vim, doc/omnisharp-vim.txt, plugin/OmniSharp.vim, test/gotometadata.vader
@nickspoons this is my pr for the goto-metadata request #303 
This adds a feature to load metadata for compiled types.
A couple of things to note here:
1. This is implemented on top of the current goto-def and is not currently exposed via a top-level command. I didn't see a need for it, but it should be possible.
2. I added to the goto-def request to bring back metadata info if availabe.
* If the goto-def does not have valid loc info, we kick of the new gotometadata methods that will send another request with the returned metadata info to get the full metadata buffer.
* It is then saved into temp file and loaded. Subsequent requests should use the same file.
3. The code supports multiple ways of presenting the metadata via the `g:OmniSharp_lookup_metadata` option.
* If it is set to …
=> GotoMetadata feature

autoload/OmniSharp/util.vim
omnisharp server usually run with system default encoding, but function `json_decode()` only accept the string arg with utf-8 encoding.
simple case is call `iconv()` before `json_decode()`, but we don't know which encoding is system default encoding, because vim could changed encoding option in vimrc.
so we can enforce server process run with utf-8 encoding alway.
like #418 which do in python mode. this is a patch for stdio mode.
i test on my windows laptop when set vim encoding with utf-8 or system default.
i have not linux/osx with dotnet develop envirment, so i can't test on other system.
If an exception occurs, add a system check statement.
=> Enforce OmniSharp server use utf-8 encoding. fix #487

python/tox-appveyor.ini
appveyor tests are failing with python2. These are running fine in
travis, and appveyor is successfully running the python3 tests so these
can be safely excluded from the appveyor suite.
=> Remove py2 tests from appveyor

autoload/OmniSharp.vim, installer/README.md, installer/omnisharp-manager.ps1
This changeset properly fixes issues caused by PowerShell's "execution policy" feature, where is blocks the execution of scripts it doesn't deem as trustworthy.
Our PowerShell installation script for the OmniSharp-Roslyn server now is executed with the `-ExecutionPolicy Bypass` flag. This flag removes the need for user to manually perform a complex series of steps.
More info on execution policies can be found here: <https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies>
The code which performed the invocation of the PowerShell script has been made significantly simpler and easier to maintain by replacing the "quotation hell" with the much simpler `-File` argument.
The arguments for the scripts all now get correctly quoted and escaped …
=> Improve reliability of the invocation of the installer scripts

autoload/OmniSharp/stdio.vim, python/omnisharp/util.py, python/tests/test_util.py
Currently we output all diagnostics received from OmniSharp-roslyn.
'Error' diagnostics are reported as "E" errors (for ALE and Syntastic, and in `:OmniSharpGlobalCodeCheck` quickfix entries) and everything else is marked as a "W" warning. Server diagnostics marked as 'Hidden' are currently sent to ALE as "W" warnings with a `"sub_type": "style"`.
However, many of the "Hidden" diagnostics are not meant to be displayed, but merely used by editors for providing notifications that refactorings etc. are available. OmniSharp-vim doesn't make use of these, so "Hidden" diagnostics will be ignored.
Instead, "Info" diagnostics (previously simply converted to "W" warnings) are now marked as "I", meaning that ALE/Syntastic can style them differently. "Info" is how "suggestions" are reported, both …
=> Update diagnostic response handling

README.md, autoload/OmniSharp/stdio.vim, doc/omnisharp-vim.txt, python/omnisharp/util.py, python/tests/test_util.py
This PR supercedes #493 which was too simplistic.
Support a new variable `g:OmniSharp_diagnostic_overrides`, a dictionary which allows users to override or ignore diagnostics by ID:
```vim
" IDE0010: Populate switch - display in ALE as `Info`
" IDE0055: Fix formatting - display in ALE as `Warning` style error
" CS8019: Duplicate of IDE0005
" RemoveUnnecessaryImportsFixable: Generic warning that an unused using exists
let g:OmniSharp_diagnostic_overrides = {
\ 'IDE0010': {'type': 'I'},
\ 'IDE0055': {'type': 'W', 'subtype': 'style'},
\ 'CS8019': {'type': 'None'},
\ 'RemoveUnnecessaryImportsFixable': {'type': 'None'}
\}
```
=> Add global diagnosic override dictionary

README.md
The following line is required in the .vimrc file for the plugin (or any such plugin) to work:
``` .vimrc
filetype indent plugin on
```
This commit adds a comment to point that out.
Fixes #494
=> Add note for required filetype statement

README.md, autoload/OmniSharp.vim, autoload/OmniSharp/stdio.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim, plugin/OmniSharp.vim
This PR provides test running functionality, using the OmniSharp-rolsyn test runner.
There are 2 commands:
1. `:OmniSharpRunTest` which runs the test method that the cursor is inside.
2. `:OmniSharpRunTestsInFile` which runs all tests in the current file, or all files passed in as arguments
`:OmniSharpRunTest` prints a "success" message if the test succeeds, and if it fails, the failure location is added to the quickfix list. `:OmniSharpRunTestsInFile` _always_ popuplates the quickfix list with all tests, so successful tests can easily be seen listed alongside failures.
Tested "mstest", "nunit" and "xunit" in gVim in Windows10 and terminal Vim in arch linux.
**Major limitation**: This will _NOT_ work via WSL. This is due to the way that the tests are run by OmniSharp-roslyn, which uses …
=> Run unit tests

autoload/coc/source/OmniSharp.vim
Should fix the same problem as in https://github.com/OmniSharp/omnisharp-vim/issues/524, but for coc.nvim. I have no idea how this remained unnoticed. (Maybe there should be more triggerCharacters, i'm not really into C#)
=> Added dot as trigger character for coc.nvim

installer/omnisharp-manager.ps1
Closes #549 
Removed `-DestinationPath` from `Expand-Archive` and used positional arguments to ensure older versions of the cmdlet work.
=> Remove named parameter from Expand-Archive

autoload/OmniSharp.vim
Fix "E119: Not enough arguments for function: <SNR>326_CBPreviewDefinition" when doing `:OmniSharpPreviewDefinition`.
In 5813d6a0, more arguments were added to CBPreviewDefinition, but they
were only added in the OmniSharp_server_stdio call site. Add empty dicts
to the second callsite to provide the required number of arguments.
Using `let g:OmniSharp_server_stdio = 1`  doesn't work at all for me, but I assume that's because I'm on Win10 with gvim? I've never tried that version, so I can't tell if that code path is also broken, but it looks correct to me.
=> Pass the correct number of arguments to preview

autoload/OmniSharp.vim
Fix #563.
OmniSharp.vim is code still runs on old versions of vim, so avoid using
v:null to maintain compatibility with vim 7.4.
v:null also appears in stdio.vim, but that feature requires more recent
vim, so it's fine.
=> Don't use v:null in core code

autoload/OmniSharp/util.vim
Fix error "Can only compare List with List" in s:StartServer when
starting vim without omnisharp server installed and declining the
install.
=> Return the correct type from GetStartCmd

autoload/OmniSharp/stdio.vim
For cross platform solutions the platform dependent projects can
fail to load. This commit prevents a timeout and therefor speeds
up the time until omnisharp becomes ready.
=> Considering failing projects on server startup to prevent timeout.

autoload/OmniSharp/stdio.vim
Previously suggestions were shown as warnings.
Do we need to worry here that other plugins might not be able to handle a 'I' type? I only checked this with ALE.
=> Info severity for codecheck results

autoload/OmniSharp/stdio.vim
The `prop_add` api of vim expects the column to be the byte offset and
not the character count. So if a comment for example would contain
a multi byte character, for example a german umlaut, then the last
character of the comment would not be included in the text property.
=> This changeset fixes syntax highlighting via text properties, if the text contains multi byte characters.

autoload/OmniSharp/stdio.vim
Since it seems impossible to get the total number of lines for a specific
buffer in vimscript, the current implementation clears the text
properties step by step with each new highlight.
When a highlight spans multiple lines and a there is another highlight
after it, the text properties of the previous multiline highlight are
being cleared.
=> Fixes the issue that only the first line of a multiline highlight has a text property set.

README.md, autoload/OmniSharp/popup.vim, doc/omnisharp-vim.txt, plugin/OmniSharp.vim, test/utils/async-helper.vader, test/utils/startserver.vader, test/vimrc
I now think the global `g:OmniSharp` dict was ill-conceived.
The idea had been that we could have a single dictionary to contain _all_ OmniSharp-vim options. The benefit would have been a clean global environment, and a consistent place to look for configuration.
However there are several problems:
1. Users aren't used to this type of configuration, so the need to initialise the dictionary is strange and will trip up ... probably everybody.
2. Declaring the config dictionary as a single command is messy with lots of backslash line continutations, but declaring the dictionary and its sub-dictionaries separately is also extra boilerplate.
3. Discoverability is reduced, as Vim won't tab-complete dictionary contents. So it is no longer possible to do `:let g:OmniSharp_<Tab>` and find/edit …
=> Roll-back global g:OmniSharp dict usage

autoload/OmniSharp/stdio.vim
This pull request fixes the issue, that empty lines were removed, while applying a quickfix. I used the following sample code to reproduce and fix the bug.
```
// Copyright © XYZ-Software, 2020
#region using directives
using System;
#endregion
namespace Project
{
public static class Program
{
public static void Main(string[] args)
{
var myArray = new int[3];
Console.WriteLine("Hello World");
myArray.Any();
}
}
}
```
The cursor is placed on the `Any()` method call, and the first Quickfix is used. The response from omnisharp-roslyn looks like this:
```
{
"Body": {
"Changes": [
{
"Buffer": null,
"Changes": [
{
"EndColumn": 2,
"EndLine": 8,
"NewText": "using System.Linq;\n\n#endregion\r\n",
"StartColumn": 1,
"StartLine": 6
}
],
"FileName": …
```
=> Bugfix for disappearing empty lines while applying quickfixes.

README.md, autoload/OmniSharp/actions/diagnostics.vim, autoload/OmniSharp/locations.vim, doc/omnisharp-vim.txt
Adds support for #504 like so:
```
let g:OmniSharp_diagnostic_exclude_paths = [
\ 'obj\\',
\ 'Temp\\',
\ '\.nuget\\'
\]
```
Before:
After:
=> Added diagnostic filter for global code check.

README.md, autoload/OmniSharp.vim, autoload/OmniSharp/actions/buffer.vim, autoload/OmniSharp/actions/diagnostics.vim, autoload/OmniSharp/actions/highlight.vim, autoload/OmniSharp/actions/highlight_types.vim, autoload/OmniSharp/actions/signature.vim, autoload/OmniSharp/actions/usages.vim, autoload/OmniSharp/actions/workspace.vim, autoload/OmniSharp/buffer.vim, autoload/OmniSharp/locations.vim, autoload/OmniSharp/log.vim, autoload/OmniSharp/proc.vim, autoload/OmniSharp/project.vim, autoload/OmniSharp/py.vim, autoload/OmniSharp/stdio.vim, autoload/OmniSharp/util.vim, autoload/ale/sources/OmniSharp.vim, doc/omnisharp-vim.txt, ftdetect/omnisharplog.vim, ftplugin/omnisharplog/OmniSharp.vim, plugin/OmniSharp.vim, syntax/omnisharplog.vim
This PR is where I'm tracking modifications to project management. Done so far:
The list of projects can be used to display "server loading progress" in the statusline - here's an example using [vim-sharpenup](https://github.com/nickspoons/vim-sharpenup), [PR#4](https://github.com/nickspoons/vim-sharpenup/pull/4):
Things I **hope** to achieve here:
**Update**: I looked into restarting the server in HTTP mode, but it requires too many changes for little gain. The entire session is set up either for HTTP or stdio including autocmds for linting engines and compatibility checks. Detecting the wrong server and stopping it cleanly with a warning message is fine.
**Note**: ~~the final point hopefully encompasses a fix for #599~~ **Update**: it does not, #599 is a WSL bug and will be fixed on the …
=> Project management

doc/omnisharp-vim.txt
The actual command doesn't have a trailing s.
=> doc: Correct name for OmniSharpPreviewImplementation

autoload/OmniSharp/actions/symbols.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim, python/omnisharp/commands.py
This new command behaves exactly like OmniSharpFindSymbol, but only for types. The main motivation was improved performance. The SymbolFilter parameter in the /findsymbols endpoint got added with the merge of pull request [#1823](https://github.com/OmniSharp/omnisharp-roslyn/pull/1823). A version of omnisharp-roslyn with
this PR included needs to be installed.
I have **only** tested the stdio codepath so far.
=> Added OmniSharpFindType command.

autoload/OmniSharp/actions/complete.vim
Hi Nick! It's been a while, but I'm back to doing some C# development. I see you've been busy! This project is a lot better than the last time I used it.
I was setting up deoplete to use the omnifunc as a completion source, but hit a crash in the fuzzy matcher because one of the complete options had `None` for the word. I checked the OmniSharp complete handler, and sure enough there was a null word sneaking in somehow. From [the docs](http://vimdoc.sourceforge.net/htmldoc/insert.html#complete-functions), word is mandatory so I think the correct fix is to filter the null value here before returning it.
=> Guard nulls in complete function

doc/omnisharp-vim.txt
Removed obsoleted instructions. Deoplete works right out of the box now with #626
=> Update doc -> Deoplete instructions

autoload/OmniSharp/actions/codeactions.vim
This prevents the code action buffer to spawn multiple times if the GetCodeActions command was used from a multiline visual selection.
Fixes #637
=> Use `range` option for codeactions

autoload/OmniSharp/actions/members.vim, autoload/OmniSharp/locations.vim
We are using the `v2/codestructure` endpoint instead of the
`/currentfilemembersasflat` endpoint here. The DisplayName of each item
in the response (elements and their children) contains the signature but
not the output type nor the modifiers like static/public/override etc.
so we are simply copying the beginning of the line in order to include
these.
Closes #609
=> Display signatures in OmniSharpFindMembers (stdio only)

installer/omnisharp-manager.sh
I fixed travis's failing test.
There was a problem in the initialization part of the variable, so I fixed it.
https://travis-ci.org/github/OmniSharp/omnisharp-vim/jobs/734638495
https://travis-ci.org/github/OmniSharp/omnisharp-vim/jobs/734692738
Could you check this PR? @nickspoons
=> [fix] failing test

.travis.yml
Hello, maintainer.
I added `Python3.8`'s test in travis-ci.
This patch can run python3.8's test in CI.
Could you check this PR?
=> [add] python3.8's test in travis

autoload/OmniSharp/actions/signature.vim
It is useful to update the signature help as new text is inserted since
it will:
* Show the most relevant overload.
* Show documentation for the currently active argument.
=> Update the signature help on `TextChangedI`

README.md, autoload/OmniSharp/actions/complete.vim, doc/omnisharp-vim.txt, plugin/OmniSharp.vim, python/omnisharp/commands.py
It can be nice to have fewer options to scroll through in a completion list. With these changes it is possible to indicate a preference for completion results without overloads. The way this is achieved is by ignoring the method signature in the completion results and only showing the method name. That, together with a `dup: 0` setting on the completion result filters down the completion list significantly.
=> Completion without overloads

ale_linters/cs/omnisharp.vim
dense-analysis/ale@5eda1df0a96e691ebf24e5d8a3585c2feb2a48a3 removed some deprecated ALE features and in doing so broke OmniSharp-Vim's HTTP integration.
=> Fix ALE HTTP mode bug

python/omnisharp/commands.py
Introduced by bd2c1a7fedf795f792016548fb768d91bf22a768.
=> Fix Python ternary syntax error

installer/omnisharp-manager.sh
I got an error when the file path contains whitespace, so I fixed it.
install.log
```
chmod: cannot access '/mnt/c/Users/FOO': No such file or directory
chmod: cannot access 'BAR/AppData/Local/omnisharp-vim/omnisharp-roslyn-v1.37.5/.msbuild/Current/Bin/Microsoft.Bcl.AsyncInterfaces.dll': No such file or directory
chmod: cannot access '/mnt/c/Users/FOO': No such file or directory
chmod: cannot access 'BAR/AppData/Local/omnisharp-vim/omnisharp-roslyn-v1.37.5/.msbuild/Current/Bin/Microsoft.Build.dll': No such file or directory
chmod: cannot access '/mnt/c/Users/FOO': No such file or directory
chmod: cannot access 'BAR/AppData/Local/omnisharp-vim/omnisharp-roslyn-v1.37.5/.msbuild/Current/Bin/Microsoft.Build.Framework.dll': No such file or directory
chmod: cannot access '/mnt/c/Users/FOO': No …
```
=> bugfix(installer): 'chmod: cannot access'

installer/omnisharp-manager.sh
As per issue #678, I've made the required change to allow for install on non-x86 devices that support mono. Tested on both an android phone and an android tv in Termux.
=> Added support for android when installing in mono mode

.github/workflows/reviewdog.yml
I added new test to check Vim script's syntax.
This unit test use `github actions` and reviewdog.
Could you check this Pull Request?
If you don't need this pull request, feel free to close it. 
> https://github.com/reviewdog/action-vint
=> [add] reviewdog's ci in github-actions

autoload/OmniSharp/actions/members.vim
The ReduceToOneCharacter function was a global function, but there was only one place where it was called, so we restricted its scope.
=> [fix] limit scope

autoload/OmniSharp.vim, autoload/OmniSharp/log.vim, doc/omnisharp-vim.txt, plugin/OmniSharp.vim
I am attempting to use omnisharp-vim as part of my nix configuration. However, omnisharp-vim tries writing logs to the plugin directory, which is in my nix store and is a read only directory.
This change adds a configuration variable for the log directory. If the configuration variable is left unset, the logs are written in the plugin directory as before. If the configuration variable is set, logs are written to the specified directory. If the directory doesn't exist, it gets created.
=> Add configuration variable for log directory

autoload/OmniSharp/actions/workspace.vim
From discussion in https://github.com/OmniSharp/omnisharp-vim/issues/386#issuecomment-923519148.
This PR makes it so that the example debugger configuration helper function I wrote in the [wiki](https://github.com/OmniSharp/omnisharp-vim/wiki/Build-command-with-autocomplete-for-.csproj-files#debugger-integration) works. Not sure when to best call it. On `OmniSharpReady` I suppose.
=> Cache Projects TargetPath from OmniSharp-Roslyn

autoload/OmniSharp/actions/buffer.vim, autoload/OmniSharp/actions/diagnostics.vim, autoload/OmniSharp/actions/signature.vim, autoload/OmniSharp/buffer.vim, autoload/OmniSharp/stdio.vim, autoload/OmniSharp/util.vim, autoload/ale/sources/OmniSharp.vim, ftplugin/cs/OmniSharp.vim, plugin/OmniSharp.vim, test/utils/async-helper.vader
This branch should hopefully provide performance improvements, while also fixing issues raised in #736 
Currently, almost all requests to the server contain the full buffer contents, keeping the server synchronised with the editor. However in very large buffers, this can cause understandably slow server interactions.
We recently stopped sending the buffer contents along with highlighting requests, and this PR also drops the buffer contents from diagnostic requests. Instead, autocmds are used to explicitly update the server buffer contents after the buffer has been edited.
The highlighting autocmds are also moved from `plugin/OmniSharp.vim` to `ftplugin/cs/OmniSharp.vim`, which gives 2 benefits:
1. Vim initialisation is improved - there is no need to create highlighting autocmds for …
=> Update buffer on change

README.md, autoload/OmniSharp/actions/project.vim, autoload/OmniSharp/actions/test.vim, autoload/OmniSharp/util.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim
This PR adds two things:
* An `OmniSharpDebugProject` command
> Launches Vimspector with an ad-hoc config targeting the current project. This will not work for any complex use-cases such as passing args or stop-on-entry of course.
* An `OmniSharpCreateDebugFile` command.
> This creates a new .vimspector configuration file in the same location of the loaded sln or dir.
@nickspoons this is not quite finished yet, I just want to get it in so you can get an idea of what I'm thinking and make early course corrections if necessary (and not insignificantly, to light a fire under me to actually get it done.)
I still need to add a vimspector check (I will find a way to share this code with the check in the existing vimspector command.)
Also, I am debating whether or not to forge forward with …
=> WIP: debug-project and create-debug file features

autoload/OmniSharp/actions/project.vim
Currently:
1. the working directory is not set which means access to runtime config files may or may not be possible
2. on windows, the targetPath is expressed with non-escaped backslashes, which makes the json value not the one the user wants
=> Improve vimspector config file generation

.github/workflows/vader.yml, README.md, autoload/OmniSharp.vim, autoload/OmniSharp/util.vim, doc/omnisharp-vim.txt, installer/omnisharp-manager.sh, plugin/OmniSharp.vim, test/vimrc
This PR adds a new variable `g:OmniSharp_server_use_net6` to support the new native dotnet net6.0 server version
=> Support the new O#-roslyn net6.0 server version

installer/omnisharp-manager.sh
Various arm64-compatible linux versions (including the base docker images for Ubuntu and Debian) report their architecture as 'aarch64' when installed on an arm64 platform (e.g., an M1 mac).  Omnisharp-vim does not recognize that architecture and so fails on the install of Omnisharp-Roslyn with "Error: architecture not supported."  In fact, however, it will work fine if the arm64 version is installed[ because the architectures are the same](https://stackoverflow.com/questions/31851611/differences-between-arm64-and-aarch64/47274698#47274698).
This minor patch causes the installer to treat aarch64 as arm64, allowing the install to proceed.
=> Install Omnisharp-Roslyn arm64 for architecture reported as aarch64

autoload/OmniSharp/actions/complete.vim
On Windows, `reltime(starttime)[0]` seems to always be `0`, while `reltime(starttime)[1]` seems to be a number of milliseconds.
From vim's doc about `reltime`:
> reltime([{start} [, {end}]])				*reltime()*
Return an item that represents a time value.  The item is a
list with items that depend on the system.  In Vim 9 script
list<any> can be used.
The item can be passed to |reltimestr()| to convert it to a
string or |reltimefloat()| to convert to a Float.
If the output of  `reltime` is OS-related, then I think the use of `reltimefloat` is justified so the behaviour is the same no matter the OS.
=> fix timeout for autocompletion on Windows

autoload/clap/OmniSharp.vim
When use vim-clap as selector ui, the list is not updated after the second time.
Once `g:clap_provider_*` is registered, vim-clap reuses it.
Changing `g:clap_provider_*` does not cause an update of the list displayed by vim-clap.
https://github.com/liuchengxu/vim-clap/blob/c1423c928d3fb4df840a85514d1d65054129e23a/autoload/clap.vim#L270-L273
To update the list in vim-clap each time, `g:clap_provider_*` must be defined only once, and `source` field must be a function that update the list.
=> Fix selector clap

autoload/OmniSharp/stdio.vim
I'm using custom script in order to rename/move a file, using dirvish.
Whenever I do that, OmniSharp has to be notified that the former buffer is obsolete and that it has to stop trying to use it.
One way of doing that is to send the information that the former buffer is empty, before the renaming/moving operation.
Omnisharp doesn't offer yet a way through its public interface to configure the `body.Arguments.Buffer` value.
I don't see a case where anyone would manually send a custom `Buffer` argument apart from an empty one, hence the implementation I'm suggesting using a `EmptyBuffer` value.
=> Allow calling /updatebuffer with an empty buffer content

autoload/OmniSharp/buffer.vim, test/fixusings.vader
Previously we used a clumsy hack to handle inserting buffer changes from the server at the end of a line. However there were cases where this still wasn't working correctly.
This change temporarily sets `virtualedit=all` (locally for the window), which simplifies the code and removes the hack.
=> Use virtualedit to simplify inserting buffer edits

autoload/OmniSharp/buffer.vim
This fixes #761 and extends #762
=> Use the file's 'bomb' for new code-action files

autoload/OmniSharp.vim, autoload/OmniSharp/actions/project.vim, autoload/OmniSharp/project.vim, autoload/OmniSharp/stdio.vim, autoload/OmniSharp/util.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim
Add new command `:OmniSharpReloadProject`, which asks omnisharp-roslyn to re-read a .csproj file and reload it, without requiring a full server restart.
The command can be used with no arguments from a .cs file. However, if the file is not currently recognised as being part of a project (e.g. it is a new, unlisted file in a .NET Framework project, perhaps having been added to the .csproj file by Unity) then omnisharp-roslyn will not know which project to reload. In this case the project should be reloaded by name.
The command accepts a project name as an argument, and provides completion for all of the projects included in the solution.
Closes #813
=> Reload project

autoload/OmniSharp/actions/complete.vim, doc/omnisharp-vim.txt, plugin/OmniSharp.vim
Hi! First of all, thanks for the amazing plugin! It has helped me a ton in my daily work.
Three months ago, I submitted an issue: #808 on omnisharp-vim not supporting snippet when used with coc. And it seems like that's because coc does not support vim source having snippets back then. But now it has added this feature with this commit: [snippet support for vim source](https://github.com/neoclide/coc.nvim/commit/e7dce3ab3e2ddf718049260690ba8686045ed1c2), and I have been playing around with omnisharp-vim's completion methods to try to add snippet support.  So far, it is working great for me, which is why I have created a pull request other people can try as well. Could you please take a look and let me know if you would be interested in adding this support and if you have any comments or …
=> Added option to enable snippet support for coc completion source. (STDIO only for now)

README.md
Github dropped supported for the unauthenticated git protocol, see: https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> Updated the clone urls from git to https in README

autoload/OmniSharp/actions/typedefinition.vim, autoload/OmniSharp/locations.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim
**OmniSharpGotoTypeDefinition** navigates to the type definition of the symbol under the cursor.
=> Add GotoTypeDefinition

autoload/OmniSharp/util.vim
When running the server with loglevel "None", no project load status messages are received. This change ensures that when loglevel is set to "None", no loglevel flag is sent to the server, so it logs at its default "Info" level and we receive project status info. We just don't write any logs to disk.
This PR supercedes #849
=> Start the server with at least minimal logging

autoload/OmniSharp/actions/complete.vim
Uses `"WantKind"` to request the completion kind from omnisharp-roslyn, and then converts that to a vim `"kind"` in the completion entry.
Fixes #865
=> Include completion "kind"
