README.md
Just to avoid this trolling people (probably me) in future, to save @nosami some time on Twitter!
=> Add note about using non-standard homebrew path

python/Completion.py, python/syncrequest.py
Using application/json http request and doing null check on returned fields.
=> Autocomplete with Omnisharp-roslyn, backward compatible with v1 server

autoload/ctrlp/OmniSharp/findcodeactions.vim, autoload/ctrlp/OmniSharp/findsymbols.vim, autoload/ctrlp/OmniSharp/findtype.vim
=> Set nolim=1 for CtrlP extensions to scroll behind to top.

autoload/OmniSharp.vim, plugin/OmniSharp.vim
diff is bits large but it is just fixing indents to EARLY RETURN.
=> Graceful failure to start server

autoload/OmniSharp.vim, plugin/OmniSharp.vim
I'm thinking this change is useful to write C# with scratch.
/cc @nosami @thinca
=> Empty code, but want to start server

plugin/OmniSharp.vim
=> Update omnisharp-rolyn to latest version on master

README.md, autoload/OmniSharp.vim, autoload/fzf/OmniSharp.vim, doc/omnisharp-vim.txt, plugin/OmniSharp.vim
I wanted support for `fzf` and thought it would be a good idea to do this as a way to familiarise myself with the code base. Please review and share your thoughts as to what else is needed in order to get this merged into mainline.
Thanks.
=> [RDY] Add support for fzf fuzzy matcher

autoload/OmniSharp.vim
To fix #280 -  sorry about that. I could not run tests because I cannot make it work, I should have made the pr only when all was working. 
Sorry for those who updated in the meantime!
=> Fix invalid if breaking json_decode

README.md
Update README.md.
- Installation instructions for OmniSharp-Roslyn on Windows.
- Minor changes to improve clarity.
=> Update README.md for installing OmniSharp-Roslyn on Windows

autoload/OmniSharp.vim
The existing 'preview' functionality did not open an actual preview window, but rather jumped through hoops to open a specific window. This is convoluted and means that builtin preview functionality is not available, such as 'previewheight' and :pclose
Closes #307 by giving the user more control over their preview window.
=> Convert __OmniSharpScratch__ to preview

README.md
README had some incorrect markdown
=> Fixed bad link markdown format

python/OmniSharp.py
=> Differentiate syntastic Errors and Warnings

.gitmodules, README.md, doc/omnisharp-vim.txt, plugin/OmniSharp.vim
As discussed in #332, this is a README rewrite recommending the OmniSharp-roslyn server instead of the old OmniSharp-server. The `server` and `roslyn` submodules have been removed, as building these from source is slow and error-prone, and roslyn has good binary releases available.
=> Rewrite README to recommend roslyn server

README.md
=> Add required libuv in README

autoload/OmniSharp.vim, doc/omnisharp-vim.txt
sorry for multiple pull requests. added helptag for using random port.
=> small documentation update. fix issue with stale code actions

autoload/OmniSharp/util.vim, python/OmniSharp.py
=> Added support for msys2 paths.

autoload/OmniSharp.vim, python/omnisharp/OmniSharp.py
Noticed that rename wasn't working properly. It needed to convert the filenames before passing them back to vim. Made a few other small quality-of-life changes in the area
=> Fix OmniSharpRename

autoload/OmniSharp.vim, doc/omnisharp-vim.txt, ftplugin/cs/OmniSharp.vim, plugin/OmniSharp.vim, python/omnisharp/OmniSharp.py, python/tests/mock_vim.py
It's incredibly helpful to be able to set the log level to info or debug and watch the log file as you run commands.
=> Add better support for debugging python code

README.md
The AppVeyor badge unfortunately can only be added by @nickspoons. See https://www.appveyor.com/docs/status-badges/.
=> Fix a minor typo and add Travis badge

autoload/OmniSharp.vim
This is nice because then you can add fallbacks like to use tags with `c-]`
=> Changed GoToDefinition to forward return value of JumpToLocation

README.md, autoload/ncm2/sources/OmniSharp.vim, plugin/OmniSharp.vim
Thought I'd test it out and see how it works.
=> Added simple autocompletion source for ncm2

installer/omnisharp-manager.sh
I was getting an error when I was trying to install on my machine.  It had an error message "unknown system MINGW64_NT-10.0"
My machine setup is Win 10, on Cmder (minimal/portable) with bash.
I added a check for MinGw so that it wouldn't error on installation.
=> Updated installer for MinGW support.

autoload/OmniSharp.vim
=> Do not skip autocmds when opening metadata

rplugin/python3/deoplete/sources/deoplete_OmniSharp.py
input_pattern was copied from deoplete-clang
Fixes #524
=> Set input pattern triggering Deoplete's completion

autoload/OmniSharp.vim
- Fix path escaping bug on Windows (and potentially Unix-likes) by using the `shellescape` function on the install path (#539)
- Add installer error logging (which I promised quite a while ago, but forgot. Sorry about that.)
- Remove duplicate installation logic.
=> Add installer error logging and escape server install path

installer/omnisharp-manager.sh
Fixes second problem in issue #506
=> Prevent custom curl user-agent strings affecting GitHub JSON response

autoload/OmniSharp/proc.vim, autoload/OmniSharp/stdio.vim
For curious people, who want to know exactly how long it took to get the server up and running.
=> Added elapsed time to server loaded message

autoload/OmniSharp/actions/highlight.vim
highlighting. Adds progress for #604, but still needs more improvements.
=> Started caching has('nvim') for performance improvements during

README.md, autoload/OmniSharp/actions/usages.vim, autoload/fzf/OmniSharp.vim, doc/omnisharp-vim.txt
=> added fzf support to OmniSharpFindUsages

autoload/deoplete/source/omnisharp.vim, rplugin/python3/deoplete/sources/deoplete_OmniSharp.py
It now will respect deoplete setting for min_pattern_length, and will also properly set the "partial" string that is passed to omnisharp server.  Without this partial string then omnisharp returns everything in global scope which leads to lag over time.  It should also make much fewer requests to omnisharp, because it will only make new requests when actually necessary.
=> (WIP) Fixed some issues with deoplete source

autoload/fzf/OmniSharp.vim, doc/omnisharp-vim.txt, plugin/OmniSharp.vim
I wanted to make my OmniSharp FZF window bigger and thought I'd implement it via a setting that I could contribute back.  Happy to make changes if needed.
=> Add g:OmniSharp_fzf_options to allow customizing FZF prompts.

README.md
I fixed ale's url in README.md
It is new URL
> https://github.com/dense-analysis/ale
=> [fix] ale's url

.github/workflows/tox.yml, .github/workflows/vader.yml
I added Github actions from travis-ci.yml
The purpose of this patch is to replace travis-ci with github-actions.
> https://github.com/kazukazuinaina/omnisharp-vim/pull/1/checks?check_run_id=3041280205
↑ this url is running result my fork repo.
=> [add] github-actions

autoload/OmniSharp/actions/complete.vim, autoload/OmniSharp/log.vim, autoload/OmniSharp/preview.vim, autoload/OmniSharp/py.vim, autoload/OmniSharp/util.vim, autoload/deoplete/source/omnisharp.vim
I added abort attribute to autoload function.
=> [add] abort attribute autoload function

.github/workflows/vint.yml
I fixed yml's syntax and suggest to supress reeviewdog's report.
After applying this patch, CI will no longer fail due to reviewdog. 
Also, the bot will automatically perform code review based on the results of static analysis. 
I think this is more suitable for our needs. 
What do you think? @nickspoons
=> [fix] reviewdog.yml

doc/omnisharp-vim.txt
=> [fix] docs typo

ftplugin/cs/OmniSharp.vim
Hello, I am back again with what is shaping up to be a weekly thing. Realized I forgot another line of code.
I am looking into doing something like the `OmniSharpDebug` command you had mentioned earlier. As I am doing the boilerplate for it I keep on coming across places that I didn't do right on the last one. 
Thanks!
=> Add delcommand for OmniSharpDebugTest

autoload/OmniSharp/popup.vim
=> neovim: Unset window-local window options on popup close

autoload/OmniSharp/actions/members.vim, autoload/fzf/OmniSharp.vim, doc/omnisharp-vim.txt
Hi!  Wanted to check if you would be interested in adding FZF support for find members.  Took a quick pass at it based on the work from find usages and it worked.  https://github.com/OmniSharp/omnisharp-vim/pull/621.
Let me know what else needs to be added and I can update the PR.
=> Add FZF support for find members

autoload/OmniSharp/actions/buffer.vim, autoload/OmniSharp/actions/diagnostics.vim
=> Wait for buffer update before checking diagnostics

autoload/OmniSharp/buffer.vim
=> Use the file's encoding for new code-action files

README.md, autoload/OmniSharp/popup.vim, doc/omnisharp-vim.txt
=> Add support for neovim floating window borders

autoload/OmniSharp/stdio.vim
=> Send trailing line to server when 'eol' is set

autoload/OmniSharp.vim, installer/omnisharp-manager.ps1
=> Respect use_net6 setting on Windows installation

autoload/OmniSharp.vim, autoload/OmniSharp/actions/complete.vim, autoload/asyncomplete/sources/OmniSharp.vim, autoload/coc/source/OmniSharp.vim, autoload/deoplete/source/omnisharp.vim, autoload/ncm2/sources/OmniSharp.vim, test/complete.vader
This PR refactors completions slightly, allowing passing completion 'startpos' locations which allows more fine-grained snippet handling.
Fixes #795
=> Snippet for generic types

autoload/OmniSharp/actions/usings.vim
=> Use the correct buffer when applying fixusings

autoload/OmniSharp/actions/project.vim
Hi @nickspoons !
While messing around with some of the debug stuff I noticed that you recently added a success arg to the callbacks in `actions/project.vim`. I changed the Debug functions to use this new success arg since they are currently failing.
Hope you are doing well!
=> Update DebugProject and CreateDebugConfig to respect success flag

autoload/OmniSharp/actions/test.vim
=> Accept extra argument from ...project#Get callback
